services:
  - type: web
    name: fmp-api
    env: docker
    plan: starter
    dockerContext: ./apps/api
    dockerfilePath: ./apps/api/docker/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: fmp-web
    env: docker
    plan: starter
    dockerContext: ./apps/web
    dockerfilePath: ./apps/web/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false
